### ISSUE TITLE
21 Numbers Online Version

### ISSUE THREAD

**Issue by TheReal20** [TheReal61/21numbers#1]
The Plus Minus Die Gets Me 19s. Please Fix This Bug

**Comment by TheReal61** [comment]
I'm still working on it, how do you have the game? I've no index file so

**Comment by TheReal20** [comment]
> I'm still working on it, how do you have the game? I've no index file so

I Am No Hack Of The. But The Game I Have. Die 19 Yellow No Gold The Bug Is Rare But May Advantage It Give.
